### ISSUE TITLE
Migrations support

### ISSUE THREAD

**Issue by tomchristie** [encode/apistar#107]
Alembic seems to be the go-to choice for SQLAlchemy, but I don't have any experience personally of eg. what the alternatives are, or how this stacks up against Django's migrations framework.

http://alembic.zzzcomputing.com/

**Comment by ddorian** [comment]
It's better than django's.

**Comment by audiolion** [comment]
@ddorian context for your reasoning?

**Comment by ddorian** [comment]
Like django just added some features on the latest version that have existed in sqlalchemy-migration for some years (custom pg indexes, functional pg indexes etc). Just like with sqlalchemy, alembic is years ahead of django in terms of features.

**Comment by tomchristie** [comment]
FWIW I think Django's migrations framework & ORM are second-to-none when it comes to developer productivity. But let's not get into a discussion of relative merits here. 

Can see that albemic is very fully featured. Not entirely obv to me what the equivalent to Django's data migrations look tho?

**Comment by audiolion** [comment]
I think we were discussing relative merits because you asked

> how this stacks up against Django's migrations framework.

Note we are not comparing SQLAlchemy to Django ORM, we are comparing Alembic to Django Migrations.

Alembic looks like it has more features and might be a bit lower level than Django migrations, but I don't think I have ever ran into a case where I wished a feature was in Django migrations, though I can see when multiple developers are making branches with schema changes, merge migrations can get messy and Alembic's support for this looks better, if not more complex.

**Comment by tomchristie** [comment]
> I think we were discussing relative merits because you asked

Fair enough - I just mean I'm not interested in "X is better than Y". Tho I am interested in which features each supports. 😄 

> though I can see when multiple developers are making branches with schema changes, merge migrations can get messy and Alembic's support for this looks better, if not more complex.

Indeed. I've found the integer incrementing to be awkward in the past, quite easy to end up introduce merge conflicts that need resolving all the time.

**Comment by maziarz** [comment]
Alembic without blinking my eyes.

**Comment by MichaelYusko** [comment]
Alembic it's cool idea, but my opinion, he has hidden obstacles.

**Comment by tomchristie** [comment]
@MichaelYusko - Okay, but help me out a bit here, so what kind of obstacles? And are they something that other migration frameworks solve or not? If so which, and how?

**Comment by MichaelYusko** [comment]
@tomchristie Sorry for my late reply
Okay, if apistar need to implement migration support, Alembic it's best way, because for now we do not have alternative for alembic.

**concerning obstacles**:
I saw a lot of cases
developer # 1 - do alembic revision, and create migration file, but then, hmmmm, I do not need this migration and delete file, okay but this migration file saved in alembic_version table,
developer # 2 - I wanna create my beautiful migration, and ooops, I Can't do migrate because developer # 1 was deleted migration file, and here start a lot of problems.

it's just my opinion;)

and when I will have free time, I necessarily will do PR.

Have a nice day.

**Comment by jairhenrique** [comment]
https://orator-orm.com/
https://orator-orm.com/docs/0.9/migrations.html

**Comment by tomchristie** [comment]
@jairhenrique - Very interesting! Likely that we'd want to see anything there as a third-party database backend with migrations support. Worth taking a look at the thread on https://github.com/tomchristie/apistar/pull/138 to see what the general approach to alternative ORMs is likely to look like.

**Comment by tomchristie** [comment]
No longer relevant since we’ve re-scoped what’s in and what’s out of core.
