### ISSUE TITLE
typesystem: Allow for more natural model definition and use

### ISSUE THREAD

**Issue by Birne94** [encode/apistar#252]
I did not find an existing issue for this yet, so here it goes..

Given a simple model for a user consisting of a name and an age:

```python
class User(Object):
    name: String
    age: Integer
```

I would like for apistar to deduce the type annotations if available and map them to the `properties` class attribute. Generally this could just be an alias (if I am not missing any cases).

```python
@property
def properties(self):
    return self.__annotations__
```

Additionally, accessing a user within a view/resource could feel much more natural by using attributes instead of item getters:

```python
def welcome(user: User):
    if user is None:
        return {'message': 'Welcome to API Star!'}
    return {'message': 'Welcome to API Star, %s!' % user.name}
```

Implementation in base class

```python
def __getattr__(self, item):
    if item in self:
        return self[item]
    raise AttributeError(item)

def __setattr__(self, key, value):
    if key in self.properties:
        self[key] = value
    raise AttributeError(key)
```

All of this can already be achieved by creating a custom base class for all models, but since (I guess) this would be a commonly used feature, official support would be nice.

**Comment by tomchristie** [comment]
It's certainly something that we'll be considering, yup.

For the moment I'd like to keep things constrained to `properties`. If/when we go down this route it'll make it more awkward to introduce any further API on the class, since any name could be used on the class namespace itself. Similar issue with allowing `user.name` over `user['name']`, since some of the properties might clash with pre-existing methods on the object, eg. `user.keys`

I'll close it off for now, but yes, it is something we may well reconsider later.
