### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by SnowWalkerJ** [encode/apistar#301]
Hi, my apache server is enabling HTTPS protocal. But this disables the application from communicating with apistar using HTTP. Is there a way to support HTTPS in APISTAR?

Thanks.

**Comment by tomchristie** [comment]
This sounds like a server configuration issue, rather than a problem in API Star.

Have a search around for eg. something like "Flask, Apache, Gunicorn, HTTPS" and base your apache configuration on that. The Apache web server should probably be handling HTTPS on the receiving end, but proxying the requests on to Gunicorn via HTTP.
