### ISSUE TITLE
`bool` query parameter coercions are surprising

### ISSUE THREAD

**Issue by ojacobson** [encode/apistar#354]
Given a handler like

```python
def foo(param: bool):
  pass
```

then invoking it with `?param=true` will set `param` to True, as expected, but invoking it with `?param=false` will _also_ set `param` to True. Coercing boolean query parameters using Python's `bool()` builtin constructor appears to be at the root of this; it's possible to set `param` to False by invoking the handler with `?param=` without a value, consistent with the result of `bool('')`.

**Comment by 7robertodantas** [comment]
In fact this problem occurs. Having a look at the apistar code, I noticed that the tests did not catch this error because it uses typesystem.Boolean instead of the primitive bool.

https://github.com/encode/apistar/blob/973c6485d8297c1bcef35a42221ac5107dce25d5/tests/typesystem/test_boolean.py#L7-L8

https://github.com/encode/apistar/blob/973c6485d8297c1bcef35a42221ac5107dce25d5/tests/typesystem/test_boolean.py#L37-L39

I am trying to find where the apistar inject the variables in view functions to see if I can help on fix it, but I couldn't find yet.

**Comment by tomchristie** [comment]
That sounds pretty broken. This is completely revisited in #400, but I think it makes sense to keep this issue open so we can verify that it’s been resolved in the next version.
