### ISSUE TITLE
'AFTER_REQUEST' throw an error when trying to use it after each request.

### ISSUE THREAD

**Issue by Bennyelg** [encode/apistar#361]
**throw an error:**
```AttributeError: 'NoneType' object has no attribute 'status'```
```
def _db_close():
    if not db.is_closed():
        db.close()

settings = {
    'BEFORE_REQUEST': [_db_open],
    'AFTER_REQUEST': [_db_close]
}
```

I tried  'AFTER_REQUEST': [_db_close()] but then I get "TypeError: None is not a callable object"

**Comment by Bennyelg** [comment]
My work around is a creating a decorator.

**Comment by randvis** [comment]
For `AFTER_REQUEST` hook, it requires 
- return a `http.Response` instance.
- at least one parameter to accept previous hook result

Try this:
```
from apistar import http
from apistar.types import ReturnValue

def _db_close(ret: ReturnValue) -> http.Response:
    if not db.is_closed():
        db.close()
    return ret
```

You can refer to code at `https://github.com/encode/apistar/blob/master/apistar/hooks.py`.

In addition, it's suggested to keep original default hook, like
`'AFTER_REQUEST': [render_response, _db_close],`

PS: I'm not sure which ORM you're using. Perhaps you can just use `Session component`, rather than manually do that by yourself.
See https://github.com/encode/apistar#backends

**Comment by tomchristie** [comment]
Closing this, given that 0.4's event hooks make this obsolete. (See #400)
