### ISSUE TITLE
Compiled regex for String patterns

### ISSUE THREAD

**Issue by rhelms** [encode/apistar#433]
The 0.4.3 API documentation at http://www.encode.io/apistar/api-guide/type-system/#serialization suggests that a String pattern can be a string or a compiled regex, as it was in 0.3.9.

However, the pattern is currently on validated as being None or being a `str`.

It seems easy enough to work around by simply making the pattern not a compiled regex. Below is my modified code that I haven't quite got to the end of testing yet because I'm still converting my app to 0.4.3.

```
class AccessSeekerRef(String):
    def __init__(self, **kwargs):
        kwargs['max_length'] = 64
        #kwargs['pattern'] = re.compile('^[0-9a-zA-Z_-]+$')
        kwargs['pattern'] = r'^[0-9a-zA-Z_-]+$'
        super(AccessSeekerRef, self).__init__(**kwargs)
```

**Comment by tomchristie** [comment]
Lets change the documention. It should only be a string. (For consistency, and in order to be able to inspect the validators easily, eg we need to use the string value when dumping validators into an equivalent JSON schema representation)

We could compile the string too, and store that value as well to use during validation, but that should be an implementation detail, and not part of the documented interface.

**Comment by tomchristie** [comment]
Docs are fixed now, and will be updated with the next released version.
