### ISSUE TITLE
ASync support

### ISSUE THREAD

**Issue by tomchristie** [encode/apistar#9]
Implement Async support, using uvloop, and a gunicorn worker class.

**Comment by graingert** [comment]
https://channels.readthedocs.io/en/stable/asgi.html
https://pypi.python.org/pypi/h11/0.5.0
https://pypi.python.org/pypi/h2/3.0.1

**Comment by tomchristie** [comment]
Thanks @graingert, those two HTTP libraries are interesting.

I'm referencing asyncio here in particular, rather than running behind an ASGI bus, but having said that, being able to run in an ASGI configuration is also *another* thing I'd like us to address at some point.

**Comment by sandys** [comment]
please consider using uvloop to increase asyncio performance - https://github.com/MagicStack/uvloop

**Comment by graingert** [comment]
uvloop is a pluggable event loop, so as long so apistar doesn't couple
itself to a specific loop implementation then it will be supported.

Sanic depends on uvloop, but I'm not sure why because it works fine with
the built in loop

On 8 Apr 2017 08:30, "Sandeep Srinivasa" <notifications@github.com> wrote:

please consider using uvloop to increase asyncio performance -
https://github.com/MagicStack/uvloop

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tomchristie/apistar/issues/9#issuecomment-292701169>,
or mute the thread

**Comment by tomchristie** [comment]
@graingert I believe uvloop is optional, but used as the default in sanic.

**Comment by tomchristie** [comment]
https://github.com/MagicStack/vmbench/blob/master/servers/asyncio_http_server.py

**Comment by ddorian** [comment]
I assume apistar should work automagically with gevent.monkey.patch_all(), right ?

**Comment by graingert** [comment]
Bit of a shame to stoop to gevent on a python 3 only framework

**Comment by sandys** [comment]
+1 on this. This would be pretty cool - gevent is still far more intuitive
then anything out there, and is quite performant.

**Comment by argaen** [comment]
@tomchristie maybe you should update the title to "Asyncio support". Like others comment adding asgi support or gevent are interesting options but IMO main focus should be for asyncio since its already stable API for the language and that's the road it will take in the future

**Comment by tryexceptpass** [comment]
@tomchristie Are you thinking of building on top of or wrapping the aiohttp web server / routing? Or are you up for having a custom asyncio.Protocol? Obviously one provides more control than the other, and if we make our own protocol then it should make the event loop backend easier to swap out between standard asyncio, uvloop and anything else that people want.

I may be able to help put this together, just need a direction in which to start.

**Comment by tomchristie** [comment]
@tryexceptpass ---> https://github.com/encode/uvicorn Describes the intended server/application interface, and an implementation against that.

**Comment by tryexceptpass** [comment]
@tomchristie Ok I forked and started to work on it. 

Trying to reuse as much as possible from uvicorn, I have a proof of concept serving both sync and async endpoints. The uvicorn project seems very basic so I didn't see anything wrong with using uvicorn directly instead of rebuilding what it does around uvloop, however I'm sure we can make some more optimizations in the future.

Things need a lot of work still, but I have been able to do the following:
* The main application in `app.py` is converted to return an async function and use an async `__call__` that uvicorn can serve.
* The pipeline in `func` makes blocking or async calls depending on whether what its calling is async defined.
* The response in `func` is written asynchronously to uvicorn's `channels['reply']`. This still needs fixes for static content.
* `http.py` was updated to retrieve parameters from the correct keys in the asgi `message`.
* Started to work on `commands/run.py` to have uvicorn execute the code, but I'm not quite there yet.

I'm using this as a basic check that things work:
```python
from apistar import App, Include, Route
from apistar.docs import docs_routes
from apistar.statics import static_routes

import asyncio
import time


def syncwelcome(name=None):
    time.sleep(10)
    if name is None:
        return {'message': 'Welcome to API Star!'}
    return {'message': 'Welcome to API Star, %s!' % name}


async def asyncwelcome(name=None):
    await asyncio.sleep(10.0)
    if name is None:
        return {'message': 'Welcome to API Star!'}
    return {'message': 'Welcome to API Star, %s!' % name}


routes = [
    Route('/', 'GET', asyncwelcome),
    Route('/sync', 'GET', syncwelcome),
    Include('/docs', docs_routes),
    Include('/static', static_routes)
]

app = App(routes=routes)
```

It helps me verify that the async route will start the countdown in parallel when multiple clients load the endpoint, while the sync route will be serialized.

Since I'm not done with `run.py`, a module like the one above must be executed with `uvicorn app:app`.

There's still work to do in logging and I haven't run the test suite yet, which I imagine will need adjustments to handle async. There's also a few things I'm doing temporarily to make things work that will need adjustments for performance.

Before I keep pushing forward, I wanted to check that this the direction you were looking for.

**Comment by tomchristie** [comment]
@tryexceptpass - That's awesome, tho we've kinda crossed streams here. I've been working towards this in #235, which allows support for *either* WSGI *or* the Uvicorn Messaging Interface.

The architecture in 0.2 also fixes being able to inject components into command line handlers, and will also allow us to provide other framework integrations too, in particular planning for flask and django.

> Since I'm not done with run.py, a module like the one above must be executed with uvicorn app:app.

Yup, same that's one of my final remaining tests. Luckily @maximilianhurl has got this pull request ready and waiting https://github.com/encode/uvicorn/pull/51, so it'll be a case of plugging that into a command.

**Comment by tryexceptpass** [comment]
I dI'd fix the run.py stuff in my fork and can run it along with the apistar cli. I'll let you guys finish things up in #235 then. Looking fwd to it.

**Comment by tomchristie** [comment]
We're there.

**Comment by ddorian** [comment]
@tomchristie so yes or no on gevent ?

**Comment by tomchristie** [comment]
@ddorian I assume that you can run the WSGI app under a gevent server implementation. This is for asyncio, tho.

**Comment by jMyles** [comment]
@tomchristie: Hey man, how are you?  :-)

So, in your mind, is the roadmap meant to specifically include flow control via the asyncio event loop?  Or are we talking about asynchronous task management fit to plug in to *any* event loop?

Although I haven't gone anywhere with it yet, I did start this project with an aim to run ApiStar in ASGI mode on Twisted:

https://github.com/jMyles/NinjaStar/

I'm very interested in bringing some of the features that we've already build in hendrix (for DRF / Twisted - https://github.com/hendrix/hendrix) to ApiStar.  I think it'll be a real shame if ApiStar relies on ayncio's event loop for flow control instead of having a pluggable system that allows users to work with Twisted instead if they want.

Of course, it may well come to pass that Twisted finally sees fit to use the asyncio event loop itself, and focus on the business of protocols and utilities.  It's not clear at this juncture, however, if asyncio will ever be a good scaffold for some of the best parts of the Twisted test infrastructure, like Trial, MemoryReactor, and Clock. 

Anyway, this is probably a bigger discussion than this ticket - is there a better place to have it?

Be well.

**Comment by tomchristie** [comment]
@jMyles Howdy! 😄 

> So, in your mind, is the roadmap meant to specifically include flow control via the asyncio event loop? Or are we talking about asynchronous task management fit to plug in to any event loop?

The support that we now have is for asyncio, which includes:

* A server/application interface that's suitable for asyncio. (This is the "uvicorn messaging interface", which is roughly based around ASGI. We need this because WSGI is designed in a way that can't work for asyncio services.)
* An asyncio server implementation that uses that interface. (This is `uvicorn`.)
* An application class that deals with providing an asyncio-compatible dependency injector, allowing handler functions to be either regular function calls or `async` declared functions. (The `ASyncIOApp` class)

> I think it'll be a real shame if ApiStar relies on ayncio's event loop for flow control instead of having a pluggable system that allows users to work with Twisted instead if they want.

If you take a look at the `WSGIApp` vs `ASyncIOApp` implementations, you'll see that there's enough flexibility to be able to wrap up other kinds of servers or server interfaces around API Star. For example, a third party could provide an `AWSLambdaApp` that translates their event interface, rather than the existing Zappa route of providing a WSGI adapter.

As I understand it from the docs, Hendrix can plug into an WSGI application (And provides some kind of implicit concurrency switching, rather than asyncio's explicit co-operative concurrency?)

> Of course, it may well come to pass that Twisted finally sees fit to use the asyncio event loop itself

I think twisted now provides a bridge to asyncio, right? I guess you could look at using that and supporting the uvicorn messaging interface in order to support asyncio application?

> Anyway, this is probably a bigger discussion than this ticket - is there a better place to have it?

Might as well take it over to https://discuss.apistar.org/ if things continue.

Hope that's enough to get going with!

**Comment by ddorian** [comment]
@tomchristie Any hope/chance for gevent ?

**Comment by tomchristie** [comment]
@ddorian There are various gevent WSGI servers (I think gunicorn includes a gevent based worker type, right?)

I assume there's no reason at all you can't already use those.
